qrcode/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('qrcodes.urls', 'qrcodes'), namespace='qrcodes')),
   
]

qrcodes/urls.py
from django.conf.urls import url
from . import views
app_name = 'qrcodes'

urlpatterns = [
			url(r'^$', views.index, name='index'),
			url(r'^topics', views.topics, name='topics'),
			url(r'^qr_topic/$', views.qr_topic, name='qr_topic'),
			url(r'^output/$', views.output, name='output'),
			]

qrcodes/models.py
from django.db import models

# Create your models here.
class qrcod(models.Model):
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add= True)

	def __str__(self):
		return self.text

	

qrcodes/forms.py
from django import forms
from .models import qrcod


class QRForm(forms.ModelForm):
	class Meta:
		model = qrcod
		fields = ['text']
		labels = {'text':''}

qrcodes/views.py
from django.shortcuts import render
from .models import qrcod
import request
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .forms import QRForm
import pyqrcode 
from pyqrcode import QRCode 
# Create your views here.

def index(request):
	return render(request,'index.html')

def topics(request):
	topics = qrcod.objects.order_by('date_added')
	context = {'topics':topics}
	return render(request, 'qrcode.html', context)
	
def qr_topic(request):
	if request.method != 'POST':
		form = QRForm()
	else:
		form = QRForm(data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('qrcodes:topics'))

	context = {'form': form}
	return render(request, 'qrform.html', context)

def output(request):
	output = qrcod.objects.latest('date_added')
	result = str(output)	
	context = {'output':output}
	url = pyqrcode.create(result)
	url.svg("vinit12.svg", scale = 8)
	return render(request,'index.html', context)

qrcodes/templates/base.html
<p>
	<a href="{% url 'qrcodes:index' %}">qrcode </a> - 
	<a href="{% url 'qrcodes:topics' %}">qrcodedata</a>

</p>

{% block content %}
{% endblock content %}

qrcodes/templates/index.html
{% extends "base.html" %}
{% block content %}
<p>qrcode</p>
<button onclick="location.href='{% url 'qrcodes:output' %}'"> Execute script</button><hr>
{% csrf_token %}
{% endblock content %}

qrcodes/templates/qrcode.html
{% extends "base.html" %}
{% block content %}

<p>QrCode</p>
<ul>
	{% for qr in topics %}
	<li> {{ qr }}</li>
	{% empty %}
	<li> No qrcode added yet</li>
	{% endfor %}

</ul>
<a href="{% url 'qrcodes:qr_topic' %}"> Add new QRCode </a>
{% endblock content %}

qrcodes/templates/qrform.html
{% extends "base.html" %}
{% block content %}
<p>Add new qr code</p>
<form action="{% url 'qrcodes:qr_topic' %}" method='POST'>
{% csrf_token %}
{{ form.as_p }}
<button name="submit">add qrcode</button>
</form>
{% endblock content %}